### ISSUE TITLE
Mr.Amir it's not working with Katana 4.0v1

### ISSUE THREAD

**Issue by EliWillyam2020** [Amir-Ashkezari/PrmanAOVs#2]
Added all environment variables and it didn't appear in katana 4.0v1, it was working perfectly in katana 3.6

**Comment by EliWillyam2020** [comment]
Mr.Amir Can you replay now, since I have a project!

**Comment by Amir-Ashkezari** [comment]
I've tested in katana4.0v1 and it works as expected. please revisit the installation instruction.

**Comment by Amir-Ashkezari** [comment]
I've upload the original script.
